agent {
    trust_domain = "sovereign.stack"
    server_address = "spire-server"
    server_port = 8084
    log_level = "INFO"
    data_dir = "/data/spire/agent"
    svid_ttl = "1h"
}

plugins {
    KeyManager "disk" {
        plugin_data {
            keys_path = "/data/spire/agent/keys.json"
        }
    }
    NodeAttestor "join_token" {
        plugin_data {
            join_token = "${SPIRE_JOIN_TOKEN}"
        }
    }
    WorkloadAttestor "unix" {
        plugin_data {}
    }
}
