{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sovereignstack.fullname" . }}-gateway
  namespace: {{ include "sovereignstack.namespace" . }}
  labels:
    {{- include "sovereignstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-backend
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - name: http-api
      port: {{ .Values.gateway.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/component: api-backend
    {{- include "sovereignstack.selectorLabels" . | nindent 4 }}
{{- end }}
