apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../k8s/base

patches:
  - target:
      kind: Deployment
      name: ss-identity
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: IDENTITY_PROVIDER
          value: "entra-id"
  - target:
      kind: Deployment
      name: ss-memory
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: STORAGE_BACKEND
          value: "azure-blob"

configMapGenerator:
  - name: azure-local-config
    files:
      - values-azure-local.yaml
